// gen_event_v21.mjs — aerial2 元絵を参照画像にして「展示会場ブース設営中の事故＋その"原因"が見える」イラストを
//   Google gemini-3-pro-image-preview のみで2枚生成（OpenAI 不使用）。
// 使い方: node gen_event_v21.mjs <baseNum> [strong]
//   collect_aerial2/aerial2_index.csv から baseNum の ファイル名/事故の型 を引き、collect_aerial2/img/<file> を参照画像として渡す。
//   出力: gen_event_v21/<baseNum>/{google_1,google_2}.png （既存>4KBは skip＝再開安全・非破壊）。
//   strong を付けると再生成用の強い原因指示で google_1b/google_2b.png（新ファイル名・上書きしない）に出力。
//   event_index_v21.csv に1行追記（既存番号行があれば追記しない）。
// 【最重要】各イラストに「事故の原因（不安全行動・不安全状態）」を転落/転倒の瞬間と同じ画面に描く。
// キー値は出力しない(.env から読む)。削除/上書き/Chrome killしない。OpenAI 経路は持たない。
import fs from "node:fs";
import path from "node:path";

const BASE = "C:/Users/kanet/20260522/safe1";
const baseNum = String(process.argv[2]||"").trim();
const STRONG = String(process.argv[3]||"").trim().toLowerCase()==="strong";
if(!baseNum){console.error("usage: node gen_event_v21.mjs <baseNum> [strong]");process.exit(2);}

function readEnv(){const o={};const p=path.join(BASE,".env");if(!fs.existsSync(p))return o;
  for(const ln of fs.readFileSync(p,"utf8").split(/\r?\n/)){const m=ln.match(/^([A-Z0-9_]+)=(.*)$/);if(m)o[m[1]]=m[2];}return o;}
const ENV=readEnv();
const GEMINI=ENV.GEMINI_API_KEY||process.env.GEMINI_API_KEY||"";
if(!GEMINI){console.error("GEMINI_API_KEY 未設定(.env)");process.exit(3);}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

// ---- CSV パース（ダブルクオート対応・最小実装） ----
function parseCsvLine(line){const out=[];let cur="",q=false;
  for(let i=0;i<line.length;i++){const c=line[i];
    if(q){ if(c==='"'){ if(line[i+1]==='"'){cur+='"';i++;} else q=false; } else cur+=c; }
    else { if(c===','){out.push(cur);cur="";} else if(c==='"'){q=true;} else cur+=c; } }
  out.push(cur);return out;}
const csvPath=path.join(BASE,"collect_aerial2/aerial2_index.csv");
const lines=fs.readFileSync(csvPath,"utf8").split(/\r?\n/).filter(Boolean);
const header=parseCsvLine(lines[0]);
const idx=k=>header.indexOf(k);
let row=null;
for(let i=1;i<lines.length;i++){const c=parseCsvLine(lines[i]);if(String(c[idx("通し番号")]).trim()===baseNum){row=c;break;}}
if(!row){console.error(`該当なし: 通し番号 ${baseNum} は CSV に存在しません`);process.exit(4);}
const refFile=row[idx("ファイル名")].trim();
const accType=row[idx("カテゴリ")].trim();
const memo=row[idx("状況メモ")].trim();
const domain=row[idx("出所ドメイン")].trim();
const refPath=path.join(BASE,"collect_aerial2/img",refFile);
if(!fs.existsSync(refPath)){console.error(`該当なし: 参照画像 ${refFile} が見つかりません`);process.exit(4);}

// ---- 番号ごとに設定した「原因シナリオ」(英語=生成用 / 日本語=記録用) ----
// その番号が無ければ事故の型ごとの既定原因にフォールバック。
const CAUSE_BY_NUM={
 "1":{ja:"高所作業車(シザースリフト)を上昇させたまま走行させ、組みかけブースのアルミトラスに激突。衝撃で手すり際の作業員がバランスを崩し手すりを越えて転落",
      en:"CAUSE (must be clearly visible in frame): the scissor lift was DRIVEN/TRAVELLED while still fully elevated and its raised platform edge SLAMS into a half-built aluminium booth truss/signage frame; the collision is happening right now and the impact throws the edge worker off balance so he is tipping/being thrown OVER the guardrail. Show BOTH the collision (the platform wedged/striking the truss, the truss frame bending) AND the worker falling over the rail in the SAME image."},
 "2":{ja:"高い看板パネルを取付けようとシザースリフトの手すりに片足を掛けて乗り上がり、身を大きく乗り出した不安全姿勢からバランスを崩して手すりを越え転落",
      en:"CAUSE (must be clearly visible in frame): to reach and fix a high signage panel a worker has PUT ONE FOOT UP ONTO THE GUARDRAIL of the scissor-lift platform and is standing/leaning far out over the rail in a clearly unsafe posture; from that posture he loses balance and is tipping head-first OVER the guardrail. Show BOTH the unsafe act (foot up on the rail, body leaning way out past the railing toward the booth panel) AND the worker falling over the rail in the SAME image."},
 "3":{ja:"シザースリフト乗降口の安全チェーン(開閉バー)を掛け忘れたまま高所作業し、開いた乗降口の側へ後退りして、ガードのない開口部からそのまま転落",
      en:"CAUSE (must be clearly visible in frame): the platform's ENTRY GATE / safety chain of the scissor lift was LEFT UNFASTENED (the entry gap in the guardrail is wide OPEN, the chain dangling unhooked); while working the worker steps/stumbles BACKWARD toward that open unguarded gap and is now falling straight out through the OPEN gate. Show BOTH the cause (the clearly open, unguarded entry gap with the dangling unhooked chain) AND the worker dropping through that gap in the SAME image."},
 "45":{ja:"作業床から組みかけブースのトラスへ直接乗り移ろうとして、シザースリフトと未固定のトラスの間で足を踏み外し、フルハーネスのフックを未接続のまま機体とブースの隙間へ転落",
      en:"CAUSE (must be clearly visible in frame): instead of repositioning the platform, the worker tries to CLIMB ACROSS / STEP OVER directly from the scissor-lift platform onto a half-built booth truss to reach a sign; his full-body harness LANYARD HOOK IS UNCONNECTED and dangles loose; the unsecured truss shifts and he MISSES HIS FOOTING, now falling into the GAP between the lift and the booth structure. Show BOTH the cause (the worker straddling/transferring from the platform to the truss with the clearly DANGLING UNHOOKED lanyard, the truss tilting) AND the worker dropping into the gap in the SAME image."},
 "64":{ja:"シザースリフトの作業床から離れた高い看板パネル/トラス上部に手を届かせようと、手すりの外へ上半身を大きく乗り出して無理に背伸び。重心が手すりの外側へ出てバランスを崩し、頭から手すりを越えて転落",
      en:"CAUSE (must be clearly visible in frame): the scissor-lift platform was NOT driven close enough to the work, so the worker LEANS HIS UPPER BODY FAR OUT past the guardrail and stretches/over-reaches with both arms toward a tall signage panel / upper booth truss that is beyond arm's reach; his centre of gravity has gone OUTSIDE the rail and he is now tipping HEAD-FIRST OVER the guardrail. Show BOTH the cause (the worker over-reaching, torso bent way out across and beyond the guardrail toward the out-of-reach booth panel, feet lifting off the platform floor) AND the worker pitching over the rail in the SAME image. This is over-reaching from the basket, NOT a foot placed up on the rail."},
 "91":{ja:"作業床の高さでは届かないブース最上部のトラス/看板に手を伸ばすため、シザースリフトの作業床の上に脚立(または裏返した運搬用コンテナ)を載せて、その上に立って更にかさ上げ。不安定な踏み台がぐらついて重心が崩れ、手すりを越えて頭から転落",
      en:"CAUSE (must be clearly visible in frame): because the raised platform was still not high enough to reach the very top of the booth truss/signage, the worker has placed a SEPARATE STEP-STOOL / SMALL STEPLADDER (or an UPTURNED transport crate) ON TOP OF the scissor-lift platform floor and is STANDING ON THAT improvised stack to gain extra height; the wobbly step tips and his centre of gravity goes over the guardrail so he is now pitching head-first OVER the rail to the hall floor far below. Show BOTH the cause (the clearly visible step-stool/crate standing on top of the platform deck, the worker balanced up on it well above the guardrail, the stool tipping) AND the worker falling over the rail in the SAME image. NOT a foot on the rail and NOT a simple lean-out — the distinguishing cause here is an improvised raised footing placed on the platform."},
 "93":{ja:"シザースリフトの作業床から、大判で重い看板パネル(展示什器)を一人で抱え上げ、手すり越しに高い位置へ取り付けようとした。重い荷の重量とぶれで重心が手すりの外側へ引っ張られ、パネルごと手すりを越えて転落",
      en:"CAUSE (must be clearly visible in frame): a single worker on the scissor-lift platform is hoisting/manhandling a LARGE, HEAVY rigid signage panel (an oversized display board) up and OUT OVER the guardrail to mount it high on the booth; the weight and swing of the bulky panel drags his centre of gravity OUTSIDE the rail and the heavy load is now pulling him — still gripping the panel — head-first OVER the guardrail. Show BOTH the cause (the clearly oversized heavy panel held out past the railing, the worker overbalanced by its weight, arms extended over the rail) AND the worker being pulled over the rail with the panel in the SAME image. The distinguishing cause here is being OVERBALANCED BY A HEAVY OVERSIZED LOAD lifted over the rail — NOT an empty-handed reach, NOT a foot on the rail, NOT a step-stool."},
 "94":{ja:"シザースリフトの延長デッキ(スライド式の張り出し床)を伸ばしたまま固定ロックを掛け忘れ、その延長部分に乗って看板へ近づこうとしたところ、未ロックのスライドデッキがずれて開いた隙間/外れた床から、作業員が手すりの外側へ踏み外して転落",
      en:"CAUSE (must be clearly visible in frame): the scissor lift's SLIDE-OUT DECK EXTENSION (the roll-out extending platform section) was pushed out but its LOCK PIN / latch was LEFT UNSECURED; the worker stepped onto that unlatched extension to get closer to the booth signage, and the unlocked sliding deck has SHIFTED/SLID OUT and dropped away, opening a gap at the platform edge — the worker is now MISSING HIS FOOTING through that opened gap and falling outside the guardrail. Show BOTH the cause (the clearly extended slide-out deck section that has come loose/shifted, the unlatched edge and the opened gap in the platform floor) AND the worker dropping through that gap in the SAME image. The distinguishing cause here is an UNLOCKED SLIDE-OUT DECK EXTENSION giving way — NOT a foot on the rail, NOT a lean-out over-reach, NOT a step-stool, NOT a heavy load."},
 "97":{ja:"シザースリフトのキャスター(車輪)ブレーキを掛けないまま上昇させて作業。作業員が看板パネルを取付けようとブースのアルミトラスを手前へ強く引き寄せた反動で、ブレーキ未固定の機体が床の上を不意に後方へ動き出し(ずれて)、その急な揺れで手すり際の作業員がバランスを崩し、手すりを越えて転落",
      en:"CAUSE (must be clearly visible in frame): the scissor lift was raised and worked on while its CASTER / WHEEL BRAKES at the base were LEFT UNLOCKED (the wheels are free, brake levers clearly in the released/up position, the lift not chocked). As the elevated worker pulls a booth aluminium truss/signage panel strongly toward himself to fix it, the unbraked lift suddenly ROLLS / SKIDS BACKWARD across the hall floor; the abrupt lurch of the whole machine throws the worker at the guardrail off balance and he is now tipping OVER the guardrail and falling. Show BOTH the cause (the lift's wheels/casters at the base clearly UNLOCKED and the whole machine visibly rolling/sliding sideways, base shifted from its position) AND the worker being thrown over the rail at the top in the SAME image. The distinguishing cause here is an UNBRAKED LIFT ROLLING at its base — NOT a foot on the rail, NOT a lean-out over-reach, NOT a step-stool, NOT a heavy load over the rail, NOT a slide-out deck."},
 "100":{ja:"組み立て途中でまだブレース固定していない背の高いブース壁パネル(自立看板)に、シザースリフトの作業床から体重をかけて寄りかかり／手で押さえながら高所作業。支えのない壁パネルが外側へ倒れ、寄りかかっていた作業員が一緒に引かれて手すりを越えて転落",
      en:"CAUSE (must be clearly visible in frame): the worker on the scissor-lift platform LEANS HIS WEIGHT ON / PUSHES AGAINST a tall FREESTANDING booth wall panel (a large display flat / partition) that is NOT YET BRACED OR FIXED — there are no diagonal braces, the panel base is loose and lifting. The unsupported wall panel TOPPLES AWAY from the platform and, because his weight is committed onto it, the worker is PULLED OVER the guardrail and falls together with the toppling panel. Show BOTH the cause (the unbraced freestanding booth wall panel tipping over, no supports at its base) AND the worker being dragged over the rail in the SAME image. The distinguishing cause here is TRUSTING/LEANING ON AN UNSECURED, UNBRACED STANDING PANEL that gives way — NOT a foot on the rail, NOT an empty-handed over-reach lean, NOT a step-stool on the deck, NOT a heavy load lifted over the rail, NOT a slide-out deck, NOT a rolling unbraked lift."},
 "104":{ja:"長いトラス材／大型看板パネルを作業床へ受け渡すため、シザースリフトの側面ガードレール(中桟)の一部を倒した／取り外したまま再固定せずに高所作業。手すりが無くなった開いた側へ作業員が後ずさり、ガードのない側面の開口部からそのまま外へ転落",
      en:"CAUSE (must be clearly visible in frame): to pass long aluminium truss members / a large signage panel up onto the scissor-lift platform, a SIDE SECTION OF THE GUARDRAIL was FOLDED DOWN / REMOVED and then LEFT UNSECURED — one side of the platform is now an OPEN, UNGUARDED EDGE with the rail bars clearly down or missing on that side (the other sides still have their rails up). While working the worker steps/backs toward that open unguarded side and is now falling straight OUT THROUGH THE MISSING-RAIL GAP at the side of the platform. Show BOTH the cause (the clearly folded-down / removed side guardrail leaving an open gap along the SIDE of the platform deck, the long truss/panel that was being loaded) AND the worker dropping out through that open side in the SAME image. The distinguishing cause here is a REMOVED / FOLDED-DOWN SIDE GUARDRAIL left unsecured (an open side edge) — NOT the entry gate/chain at the access point, NOT a foot on the rail, NOT an over-reach lean, NOT a step-stool, NOT a heavy load lifted over an intact rail, NOT a slide-out deck, NOT a rolling lift, NOT leaning on a wall panel."},
 "112":{ja:"作業を終え、上昇したシザースリフトをいちいち下降させる手間を惜しんで、手すりを乗り越え、機体のシザース機構(X字フレーム)に足を掛けて外側からよじ降りて高所のまま降りようとした。手すりにまたがった不安定な体勢で足を滑らせ、リフトの外側を伝う途中で手が離れて床まで転落",
      en:"CAUSE (must be clearly visible in frame): instead of lowering the elevated scissor lift to get down, the worker — to save time — is DISMOUNTING AT HEIGHT by CLIMBING OUT OVER the intact top guardrail and trying to CLIMB DOWN THE OUTSIDE OF THE MACHINE, putting a foot onto the scissor lift's X-shaped SCISSOR ARMS / cross-frame as if it were a ladder. Straddling the guardrail in this unstable posture his foot slips off the scissor frame and his hands lose grip, so he is now falling down the OUTSIDE of the elevated lift toward the exhibition-hall floor. Show BOTH the cause (the worker clearly CLIMBING OVER the top rail and stepping onto the X-scissor cross-arms on the outside of the raised machine to climb down, the lift still fully elevated, the guardrail otherwise intact and the access gate NOT used) AND the worker peeling off the outside of the lift in the SAME image. The distinguishing cause here is UNSAFE DISMOUNTING — climbing over the rail and down the scissor mechanism instead of lowering the platform — NOT reaching for a sign, NOT transferring onto a booth truss to work, NOT a foot-on-rail over-reach, NOT a step-stool, NOT a heavy load, NOT a removed side rail, NOT an open entry gate."},
 "114":{ja:"フルハーネスを着用してはいたが、命綱(ランヤード)のフックをアンカー(手すり/親綱)へ接続しないまま高所作業。手すり際で看板取付け中に体勢を崩して手すりを越えたが、未接続のフックが宙ぶらりんで落下を止められず、そのまま床まで転落",
      en:"CAUSE (must be clearly visible in frame): the worker IS wearing a full-body safety harness BUT his fall-arrest LANYARD HOOK / CARABINER WAS NEVER CLIPPED to any anchor — the hook hangs FREE and DANGLING at the end of the slack lanyard, and the guardrail/anchor point is clearly EMPTY with nothing attached. While working at the platform edge he overbalances and goes OVER the guardrail; because the lanyard is UNCONNECTED it arrests nothing and he is now falling all the way to the exhibition-hall floor. Show BOTH the cause (the harness lanyard's hook hanging loose and UNATTACHED, swinging in mid-air, the anchor rail clearly bare) AND the worker dropping past the rail with the useless dangling lanyard trailing him in the SAME image. The distinguishing cause here is FALL-ARREST HARNESS LEFT UNCLIPPED (lanyard not connected to an anchor) — NOT climbing across onto a booth truss, NOT a foot on the rail, NOT an over-reach lean, NOT a step-stool, NOT a heavy load, NOT a removed side rail, NOT an open entry gate, NOT unsafe dismounting down the scissor frame."},
 "137":{ja:"シザースリフトの作業床の上に、工具・電動ドライバー・とぐろを巻いた延長コード・看板パネルの端材などを片付けずに散乱させたまま高所作業。手元の看板取付けに気を取られた作業員が後ずさりした際、足元に転がる工具や延長コードに足を取られてつまずき、その勢いのまま手すりを越えて転落",
      en:"CAUSE (must be clearly visible in frame): the scissor-lift platform DECK IS CLUTTERED — power tools, a cordless drill, a coiled extension cord/cable, leftover signage-panel offcuts and a stray bucket are LEFT LYING LOOSE ALL OVER THE PLATFORM FLOOR (poor housekeeping). Absorbed in fixing a booth signage panel, the worker steps BACKWARD, his foot CATCHES / TRIPS on the loose tools and coiled cord underfoot, and the trip pitches him backward OVER the guardrail so he is now falling to the exhibition-hall floor. Show BOTH the cause (the clearly visible clutter of tools, coiled extension cord and offcuts strewn across the platform deck, the worker's foot tangled/tripping on them) AND the worker toppling over the rail in the SAME image. The distinguishing cause here is TRIPPING ON CLUTTER / TOOLS LEFT ON THE PLATFORM DECK (bad housekeeping) — NOT a foot deliberately on the rail, NOT an over-reach lean, NOT a step-stool used for height, NOT a heavy load over the rail, NOT a removed side rail, NOT an open entry gate, NOT an unclipped harness, NOT unsafe dismounting."},
 "138":{ja:"シザースリフトの作業床に、こぼした塗料／開いたペンキ缶やペットボトルの水がたまった濡れて滑りやすい床面を放置したまま高所作業。看板パネルの取付けで踏ん張った瞬間に濡れた床で足が前へ滑り、踏ん張りが利かないまま体が流れて手すりの下／外へ滑り落ちて転落",
      en:"CAUSE (must be clearly visible in frame): the scissor-lift platform DECK IS WET AND SLIPPERY — a spilled liquid puddle is pooled across the metal deck floor (an OPEN tipped-over paint can / spilled water bottle with a visible glossy wet sheen and a slick spreading puddle on the platform floor), left uncleaned. As the worker plants his feet and pushes to fit a booth signage panel, his boot SLIPS forward on the slick wet deck, his footing gives way and — unable to catch himself — his body slides and is thrown OUT and DOWN under/over the guardrail, so he is now falling to the exhibition-hall floor. Show BOTH the cause (the clearly visible glossy WET PUDDLE / spilled liquid spreading across the platform deck and the tipped paint can/bottle, the worker's boot skidding out from under him on the wet surface) AND the worker sliding off the platform past the rail in the SAME image. The distinguishing cause here is a SLIP ON A WET / SLIPPERY DECK (spilled liquid left on the platform floor) — NOT tripping on loose tools/clutter, NOT a foot deliberately on the rail, NOT an over-reach lean, NOT a step-stool used for height, NOT a heavy load over the rail, NOT a removed side rail, NOT an open entry gate, NOT an unclipped harness, NOT unsafe dismounting, NOT leaning on an unbraced panel."},
 "196":{ja:"作業床の高さでは届かないブース最上部の看板/トラスに手を届かせようと、シザースリフトの上部手すりの最上段に両足で立ち上がり（手すりの上に登って足場代わりにする）、不安定な体勢で背伸びした瞬間にバランスを崩し、手すりの外側へ落下して転落",
      en:"CAUSE (must be clearly visible in frame): to reach the very top of a tall booth signage/truss that the raised platform still cannot reach, the worker has CLIMBED UP AND IS STANDING WITH BOTH FEET ON TOP OF THE GUARDRAIL ITSELF (using the top rail of the scissor-lift platform as a footing / standing balanced on the narrow top rail), well above the platform deck; from this extremely unstable perch he overbalances and is now pitching OUTWARD and falling off the OUTSIDE of the platform toward the exhibition-hall floor. Show BOTH the cause (the worker clearly STANDING UP ON TOP OF THE GUARDRAIL with both boots on the top rail, the platform deck empty below his feet) AND the worker toppling off and falling in the SAME image. The distinguishing cause here is STANDING ON TOP OF THE GUARDRAIL (climbing onto the rail to gain height) — NOT merely putting one foot up while leaning, NOT an empty-handed over-reach lean from inside the basket, NOT a separate step-stool placed on the deck, NOT a heavy load over the rail, NOT a removed side rail, NOT an open entry gate, NOT an unclipped harness, NOT tripping on clutter, NOT a wet deck slip, NOT unsafe dismounting down the scissor frame."},
 "215":{ja:"一台のシザースリフトの狭い作業床に、定員/積載荷重を超えて複数の作業員(3〜4人)と看板パネル・工具を一度に詰め込んで同時作業(過積載・定員オーバー)。混み合った床で互いの身体や運び込んだ荷物が押し合い、手すり際の作業員が他の作業員/パネルに押されて(玉突きで)バランスを崩し、手すりの外側へ押し出されて転落",
      en:"CAUSE (must be clearly visible in frame): the small scissor-lift platform is OVERCROWDED / LOADED BEYOND ITS RATED CAPACITY — TOO MANY workers (three or four people) are crammed onto the platform deck at once TOGETHER WITH large signage panels and tool boxes, so the deck is jammed full and people are shoulder-to-shoulder with no room. In the crush the workers and the carried panels JOSTLE and PUSH against each other, and the worker at the edge is SHOVED / forced against the guardrail by the crowding behind him, loses balance and is now being PUSHED OUT OVER the guardrail, falling to the exhibition-hall floor. Show BOTH the cause (the platform clearly OVERPACKED with several workers and bulky panels crowding every inch of the deck, bodies pressed together pushing the edge worker outward) AND that edge worker being pushed over the rail and falling in the SAME image. The distinguishing cause here is OVERCROWDING / EXCEEDING THE RATED PLATFORM CAPACITY (too many people and materials on one lift) — NOT a single worker's foot on the rail, NOT an over-reach lean, NOT standing on the rail, NOT a step-stool, NOT a single heavy load lifted over the rail, NOT a removed side rail, NOT an open entry gate, NOT an unclipped harness, NOT tripping on clutter, NOT a wet deck slip, NOT unsafe dismounting, NOT leaning on an unbraced panel, NOT a rolling unbraked lift."},
 "372":{ja:"上方のブース最上部トラス/天井梁を見上げて看板を取付け中、操作盤の上昇レバー(ジョイスティック)を身体/腹で押したまま気づかず連続上昇させ続ける『意図しない連続操作(サステインド・インボランタリー・オペレーション)』。前かがみで頭・首・胸が手すりの上端と直上のアルミトラス/天井梁との間に入り込み、上昇し続けるシザースリフトに挟まれて押し潰される",
      en:"CAUSE (must be clearly visible in frame): ACCIDENT TYPE IS A CRUSH / CAUGHT-BETWEEN (NOT a fall — nobody falls off here). The worker on the scissor-lift platform is looking UP to fit a high booth signage / aluminium truss and, while bent forward, his TORSO/BELLY IS LEANING AGAINST THE PLATFORM CONTROL PANEL and his body is UNINTENTIONALLY HOLDING THE UP JOYSTICK/LEVER PRESSED — 'sustained involuntary operation' — so the scissor lift KEEPS RISING by itself. He does not notice, and his bent-forward HEAD / NECK / CHEST gets driven INTO THE NARROWING GAP between the platform's TOP GUARDRAIL and the OVERHEAD aluminium booth truss / ceiling beam directly above, so he is being PINNED AND CRUSHED between the rising platform rail and the overhead structure right now. Show BOTH the cause (the control panel with the UP lever/joystick clearly being pressed/pinned by the worker's body, the scissor lift still elevating, the X-scissor mechanism extended) AND the crush moment (the worker's head/upper body trapped and squeezed between the top guardrail and the overhead truss/beam) in the SAME image. The distinguishing cause here is SUSTAINED INVOLUNTARY OPERATION OF THE UP CONTROL while looking up, crushing the operator against an overhead obstruction — it is a CRUSH between the platform and the structure overhead, NOT a fall from height, NOT a hand caught in the scissor linkage. No blood/gore."},
 "379":{ja:"作業床から離れた位置にある組みかけブースの固定アルミトラス支柱(自立した構造体)へ手を伸ばして看板金具を取付けようと、シザースリフトを上昇させながら身を乗り出して作業。上昇し続ける作業床の手すりと、すぐ脇に立つ固定トラス支柱との間に、乗り出した作業員の腕/胴体が横方向から入り込み、狭まる隙間に挟まれて押し潰される(側面の挟まれ・巻き込まれ)。落下ではなく、上昇する機体と固定構造物の間の挟圧。",
      en:"CAUSE (must be clearly visible in frame): ACCIDENT TYPE IS A CRUSH / CAUGHT-BETWEEN (NOT a fall — nobody falls off here). A worker on the scissor-lift platform LEANS/REACHES SIDEWAYS toward a FIXED, free-standing aluminium booth TRUSS COLUMN / structural post that stands right beside the platform, to fasten signage brackets; the scissor lift KEEPS RISING while he is leaning out, and his REACHING ARM / TORSO gets driven INTO THE NARROWING SIDE GAP between the platform's rising TOP GUARDRAIL and the adjacent FIXED truss column, so he is being PINNED AND CRUSHED LATERALLY between the moving platform rail and the fixed structure right now. Show BOTH the cause (the scissor lift clearly still elevating with its X-scissor mechanism extended, the worker leaning out across the rail toward the rigid fixed truss column close alongside) AND the crush moment (the worker's arm/upper body trapped and squeezed in the closing gap between the top guardrail and the fixed truss post) in the SAME image. The distinguishing cause here is a LATERAL CRUSH between a RISING platform and an ADJACENT FIXED booth structure while reaching out — it is a CRUSH/caught-between, NOT a fall from height, NOT a hand caught inside the scissor linkage, and DIFFERENT from an overhead crush against a ceiling beam. No blood/gore."},
 "497":{ja:"上昇させたままのシザースリフトを搬入口の床ケーブル/段差(配線カバー・スロープの継ぎ目)の上を走行させ、片側のキャスターが太い床ケーブル束/段差に乗り上げて機体が大きく傾く。重心の高い上昇状態のまま片輪が浮き、支えを失った機体が横方向へ倒れていく(横転)。アウトリガー/接地が不十分なまま段差を越えたことが原因。",
      en:"CAUSE (must be clearly visible in frame): ACCIDENT TYPE IS A TIP-OVER / OVERTURN of the machine (NOT a person falling off an intact upright lift). The scissor lift is FULLY ELEVATED and was DRIVEN/TRAVELLED across the exhibition-hall floor over an OBSTRUCTION — one of its base CASTERS HAS RIDDEN UP onto a thick run of FLOOR CABLES / a cable-cover ramp / a small floor step (loading-dock threshold) — so ONE WHEEL IS LIFTED and the base is no longer level. With its high centre of gravity raised, the whole machine has lost stability and the ENTIRE SCISSOR LIFT IS TIPPING / OVERTURNING SIDEWAYS, the elevated platform with the worker on it swinging over as the machine falls. Show BOTH the cause (the base wheel/caster clearly RIDDEN UP onto the visible thick floor cable bundle / cable ramp / floor step under it, the base tilted off level) AND the moment of the whole lift overturning with the worker riding the toppling platform, in the SAME image. The distinguishing feature here is the MACHINE ITSELF OVERTURNING because a wheel rode up a floor obstruction / uneven ground (a tip-over), NOT a worker tipping over an otherwise-stable guardrail, NOT a crush, NOT an over-reach fall. No blood/gore."},
 "518":{ja:"平らな床に据えたシザースリフトを最大まで上昇させた状態で、作業床の作業員が、ずれて建っている重い組みかけブースの壁パネル/自立トラスを手で強く手前へ引き寄せて(あるいは固定構造物を強く押して)位置合わせし、高所で大きな水平力を機体にかけた。重心の高い上昇姿勢のまま水平方向の反力でバランスの支点を越え、床は平らなのに機体全体が水平力をかけた向きへ横転していく(側方水平力による転倒・横転)。床の段差やケーブルへの乗り上げが原因ではなく、上昇中の高所での水平押し引きが原因。",
      en:"CAUSE (must be clearly visible in frame): ACCIDENT TYPE IS A TIP-OVER / OVERTURN of the whole machine (NOT a person falling off an otherwise-stable upright lift, NOT a crush). The scissor lift stands on FLAT, LEVEL floor and is FULLY ELEVATED to near its maximum height. The worker on the platform is applying a LARGE HORIZONTAL FORCE at height — he is HAULING/PULLING a heavy mis-aligned half-built booth wall panel / free-standing aluminium truss strongly TOWARD the platform (or shoving hard against a fixed booth structure) to drag it into position, both arms straining, body braced against the rail. This big SIDE / HORIZONTAL force at the top of the tall raised machine overcomes its stability: with its high centre of gravity, the ENTIRE SCISSOR LIFT is now OVERTURNING SIDEWAYS in the direction of the push/pull, the base wheels on the far side LIFTING clear off the flat floor, the elevated platform and worker swinging over as the whole machine topples. Show BOTH the cause (the worker clearly hauling/pushing the heavy booth panel/truss with a strong horizontal pull at full height, the lift's far-side base wheels lifting off an obviously FLAT, UNOBSTRUCTED floor — NO cable or step under the wheels) AND the moment of the whole lift overturning, in the SAME image. The distinguishing cause here is HORIZONTAL / SIDE LOADING AT HEIGHT (pushing or pulling a fixed/heavy object from the elevated platform) overturning the high-CG machine on level ground — NOT a wheel riding up a floor cable/step/obstruction, NOT uneven ground, NOT a worker tipping over an intact guardrail, NOT a crush. No blood/gore."},
 "519":{ja:"シザースリフトを平らな床ではなく搬入口のスロープ/傾斜路(ローディングドックの登り勾配・仮設スロープ)の上に据えたまま作業床を高く上昇させて高所作業。地面そのものが傾いているため、上昇して重心が高くなった機体は最初から斜めに立っており、わずかな作業反動だけで安定支点を越え、機体全体が勾配の下り方向へ転倒・横転していく(傾斜地での上昇=不整地・接地不良起因の横転)。497の『平床で片輪が太いケーブル束/段差に乗り上げて片側だけ浮く』のとも、518の『平らな水平床で高所から強く水平に押し引きする』のとも異なり、原因は『地面が傾いたスロープ/傾斜路の上で上昇させたこと』そのもの。",
      en:"CAUSE (must be clearly visible in frame): ACCIDENT TYPE IS A TIP-OVER / OVERTURN of the whole machine (NOT a person falling off an otherwise-stable upright lift, NOT a crush). The scissor lift has been set up and FULLY ELEVATED while standing on a SLOPED / INCLINED SURFACE — a loading-dock RAMP / temporary access slope at the hall entrance — instead of on flat level floor; the GROUND ITSELF IS TILTED. Because the whole base sits on the incline, once the platform rises and the centre of gravity goes high, the entire machine is already leaning down-slope and only a small work reaction is enough to push it past its stability point, so the ENTIRE SCISSOR LIFT IS NOW OVERTURNING / TOPPLING SIDEWAYS DOWN THE SLOPE, the elevated platform and the worker swinging over as the machine falls. Show BOTH the cause (the lift's base clearly standing on a visibly INCLINED ramp / sloped floor — the whole base tilted because the ground under all the wheels is a slope, NOT a single wheel riding up a discrete cable/step on otherwise flat floor) AND the moment of the whole lift overturning down-slope with the worker riding the toppling platform, in the SAME image. The distinguishing cause here is ELEVATING THE LIFT ON SLOPED / INCLINED GROUND (a ramp), overturning the high-CG machine because the ground is tilted — NOT a wheel riding up a thick floor cable/step on level ground (that is 497), NOT horizontal push/pull side-loading on flat level ground (that is 518), NOT a worker tipping over an intact guardrail, NOT a crush. No blood/gore."},
};
const CAUSE_BY_TYPE={
 "墜落・転落":{ja:"手すりに足を掛けて/身を乗り出して無理な姿勢で看板を取付け、バランスを崩して手すりを越え転落",
   en:"CAUSE (visible): a worker on the scissor-lift platform OVERREACHES far out / puts a foot on or leans over the guardrail to fix a signage panel, loses balance and tips over the rail. Show the unsafe overreaching posture AND the fall together."},
 "転倒・横転":{ja:"アウトリガー/接地不良または床の段差・ケーブルに片輪が乗り上げ、上昇中のシザースリフトが傾いて横転",
   en:"CAUSE (visible): the scissor lift tips/overturns because one wheel has ridden up onto a floor step/gap or a thick cable run, OR it stands on uneven ground; show the tilted lift AND the visible floor step/cable/uneven ground underneath that caused it."},
 "挟まれ":{ja:"下降操作中に身体/手をシザース機構の隙間に入れて挟まれる、または重い什器・パネルとの間に挟まれる",
   en:"CAUSE (visible): while the scissor mechanism is being lowered a worker's hand/body is inside the closing scissor linkage (or pinched between a heavy panel and a fixture); show the body part caught at the pinch point AND the moving mechanism."},
 "不安全行動":{ja:"フルハーネスのフック未接続のまま手すりに立つ/構造物へ乗り移ろうとして転落",
   en:"CAUSE (visible): the worker performs an unsafe act — standing on the guardrail or trying to climb across onto the booth structure with the harness hook UNCONNECTED (dangling); show the dangling unhooked lanyard AND the worker falling."},
 "感電":{ja:"展示用照明/電源配線を活線のまま触り感電、上で身体がのけぞり墜落",
   en:"CAUSE (visible): the worker touches live exhibition lighting/power wiring; show the contact with the wiring AND the worker recoiling/falling from the platform."},
 "飛来・落下":{ja:"上で固定不十分なトラス材/看板パネルが落下し下の作業員に直撃",
   en:"CAUSE (visible): an unsecured truss bar / signage panel slips from the height; show it dropping from the unfinished structure AND striking the worker below."},
 "その他":{ja:"ブース設営中の不安全状態によりシザースリフト上の作業員が被災",
   en:"CAUSE (visible): a clear unsafe condition/act on a scissor lift during booth setup is shown together with the resulting accident moment."},
};
const sceneKey=CAUSE_BY_TYPE[accType]?accType:(Object.keys(CAUSE_BY_TYPE).find(k=>k!=="その他"&&(accType.startsWith(k)||accType.includes(k)))||"その他");
const cause=CAUSE_BY_NUM[baseNum]||CAUSE_BY_TYPE[sceneKey];

// ---- 統一スタイル ----
const STYLE=[
 "High-quality, realistic Japanese workplace-safety educational illustration (clean professional art with rich shading, depth and a sense of presence). Do NOT imitate the source picture's drawing style; only inherit its accident TYPE. The source image is a reference for the hazard type only.",
 "Setting: a JAPANESE EXHIBITION HALL / trade-show booth SETUP site (half-built exhibition booths, aluminium truss frames, large blank signage panels, display fixtures, cardboard crates, floor cable runs and small floor steps, a loading dock in the background).",
 "Workers: Japanese exhibition crew wearing chin-strap helmets, hi-vis vests, work gloves and safety boots; when at height they wear a full-body safety harness.",
 "Any aerial work platform MUST be a SCISSOR LIFT only (vertical scissor-type elevating platform). Never a boom lift or truck-mounted boom.",
 "Absolutely NO text, NO letters, NO numbers, NO arrows, NO captions, NO speech bubbles, NO symbols anywhere. No blood/gore. No real brand names or real logos. Proper PPE on workers.",
].join(" ");
const MOST_IMPORTANT="MOST IMPORTANT: this is a CAUSE-AND-EFFECT safety illustration. The viewer must instantly understand WHAT WENT WRONG. Draw the accident MOMENT (the fall / tip-over / being struck) AND the CAUSE (the unsafe act or unsafe condition) TOGETHER in the same frame. Do NOT draw a person merely falling through empty air with no visible cause.";
const STRONG_EXTRA=STRONG?" EXTRA EMPHASIS: the previous attempt failed because the CAUSE was not visible. Make the unsafe condition/act unmistakably large and central in the foreground, clearly connected to why the person is falling.":"";
const VARIANTS=[
 "Composition A: wide angle showing the whole scissor lift, the half-built booth and the cause-object clearly, with the worker at the accident moment.",
 "Composition B: closer dramatic angle that still keeps BOTH the cause and the falling/struck worker visible in frame.",
];
const buildPrompt=(vi)=>`${cause.en} ${MOST_IMPORTANT}${STRONG_EXTRA} ${STYLE} ${VARIANTS[vi%VARIANTS.length]}`;

// ---- 参照画像 ----
const refBuf=fs.readFileSync(refPath);
const refMime=refFile.toLowerCase().endsWith(".png")?"image/png":refFile.toLowerCase().endsWith(".webp")?"image/webp":refFile.toLowerCase().endsWith(".gif")?"image/gif":"image/jpeg";

async function genGoogle(prompt){
  const model="gemini-3-pro-image-preview";let last="";
  for(let a=0;a<4;a++){try{
    const body={contents:[{parts:[{inlineData:{mimeType:refMime,data:refBuf.toString("base64")}},{text:prompt}]}],generationConfig:{responseModalities:["IMAGE"]}};
    const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":GEMINI},body:JSON.stringify(body)});
    if(r.status===429||r.status>=500){last=`http ${r.status}`;await sleep(3500*2**a);continue;}
    const j=await r.json();const parts=j?.candidates?.[0]?.content?.parts||[];
    const img=parts.find(p=>p.inlineData?.data||p.inline_data?.data);
    if(img)return(img.inlineData||img.inline_data).data;
    last=j?.error?.message||JSON.stringify(j).slice(0,200);
    if(/RESOURCE_EXHAUSTED|quota|rate/i.test(last)){console.error("RATE/QUOTA:",last.slice(0,120));await sleep(4000*2**a);continue;}
    await sleep(2500*2**a);
  }catch(e){last=e.message;await sleep(2500*2**a);}}
  throw new Error("google: "+last);
}

const outDir=path.join(BASE,"gen_event_v21",baseNum);
fs.mkdirSync(outDir,{recursive:true});
const sfx=STRONG?"b":"";
const jobs=[
  {name:`google_1${sfx}.png`,fn:()=>genGoogle(buildPrompt(0))},
  {name:`google_2${sfx}.png`,fn:()=>genGoogle(buildPrompt(1))},
];
let ok=0,failed=[];
for(const j of jobs){
  const out=path.join(outDir,j.name);
  if(fs.existsSync(out)&&fs.statSync(out).size>4000){console.log("skip(exists)",out);ok++;continue;}
  try{const b64=await j.fn();fs.writeFileSync(out,Buffer.from(b64,"base64"));console.log("saved",out);ok++;}
  catch(e){console.error("FAIL",j.name,"-",String(e.message).slice(0,160));failed.push(j.name);}
}

// ---- event_index_v21.csv 追記（既存番号行があれば skip・通常生成時のみ） ----
if(!STRONG){
  const idxCsv=path.join(BASE,"gen_event_v21","event_index_v21.csv");
  const idxHeader="元番号,元ファイル,元の事故の型,設定した原因シナリオ,生成タイトル,google_1,google_2\n";
  if(!fs.existsSync(idxCsv))fs.writeFileSync(idxCsv,idxHeader);
  const existing=fs.readFileSync(idxCsv,"utf8").split(/\r?\n/).some(l=>parseCsvLine(l)[0]===baseNum);
  if(!existing&&failed.length===0){
    const title=`展示会場ブース設営中の${accType}事故（原因が見える）`;
    const esc=s=>`"${String(s).replace(/"/g,'""')}"`;
    const line=[baseNum,refFile,accType,cause.ja,title,"google_1.png","google_2.png"].map(esc).join(",");
    fs.appendFileSync(idxCsv,line+"\n");
    console.log("index appended",baseNum);
  }
}
console.log(`DONE base=${baseNum} type=${accType} ref=${refFile} domain=${domain} strong=${STRONG} cause="${cause.ja}" ok=${ok}/2 failed=${failed.join(",")||"none"}`);
process.exit(failed.length?1:0);
